### ISSUE TITLE
Rename OTelSpan & JaegerTracer in Tests

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#112]
Our main testing `Span` and `TracingInstrument` are named after specific potential implementations, but has by no means the goal of implementing their complete functionality. This might be confusing to others looking at our test code. Let's rename them to something like `TestSpan` & `TestTracer`. @ktoso WDYT?

**Comment by ktoso** [comment]
Oh great, I just said the same thing in another comment :) 

Yes, sounds very good.
