### ISSUE TITLE
Revisit addLink parameter wording (it should not be `parent`?)

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#117]
The span passed to add link does not have to necessarily be a parent;

> When using the scatter/gather (also called fork/join) pattern, the root operation starts multiple downstream processing operations and all of them are aggregated back in a single Span. This last Span is linked to many operations it aggregates.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md#links-between-spans

today we have it as `public mutating func addLink(_ parent: Span, attributes: SpanAttributes = [:]) {` it should be `_ other` I guess, parent implies too much here. It may or may not be a parent.

**Comment by slashmo** [comment]
Yep, thanks 👍 I'll change it to `other`.
