### ISSUE TITLE
Force Spans to be classes?

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#119]
I remain on the fence about it... So far I've seen a few implementation implementations of tracers and only one of them uses structs for spans, though it's also very simplistic and should really also be a class. (All notable impls, xray and a few others I looked into though cannot share are really best implemented by classes).

Most specifically, this is more about the functions being mutating and that then we have `var span` and we change that, rather than mutating the span which does not feel as natural. Context is different because it's a bag of values and naturally has value semantics, but spans not really -- and spans _do_ want `deinit` because they _do_ want to report any dropped spans.

Specifically in patterns like this:

```
var/let span = tracer.startSpan("...", context: context)

someAsync { 
  someAsync { span.end() } // double ending, bad!
  span.end() // "mutating" because sets flags/timestamps
}
```

the value semantics actually are not so good here, because we'd also want to detect a double `end()`, and open telemetry advices:

> Implementations MUST ignore all subsequent calls to End (there might be exceptions when Tracer is streaming event and has no mutable state associated with the Span).

So yeah, that basically means spans are mutable so might as well embrace it -- forcing all spans to be classes.

Any concerns about this?

**Comment by slashmo** [comment]
Agreed, also in comparison with  `BaggageContext`. `Span` is more like a way to (abstractly) signal something to a `TracingInstrument` rather than an actual value that you feed through the system. 

### Action

The only thing we'd have to do to force classes is `protocol Span: AnyObject`, right?

**Comment by ktoso** [comment]
Yes that's how we'd do it -- I'll make a round of more sanity checking that will work well or has some hidden traps along the way.

CC @pokryfka as well, this means strongly preferring a direct `Segment: Span` conformance, without wrappers. I don't recall why you proposed doing a wrapper if necessary? AFAICS the XRay impl also is a class (for good reason).

**Comment by pokryfka** [comment]
> AFAICS the XRay impl also is a class (for good reason).

`XRayRecorder.Segment` is a reference type, it was a value type in the very first implementation as I though it'd be the right way to do it but soon I found it impractical:

- segment (span) state (ended, emitted) consistency - although this could be delegated to `XRayRecorder` which is an instance (in my implementation segments have a callback and the actual logic is in recorder instance)
- deinit - I do check if segment was ended and emitted here, even though the only consequence if that's not the case is a warning message
- segment data consistency, with struct you could end up with (logically that is having the same id) "the same" segment (span) end up having different data, example:

```swift
var span: Span
var spanCopy = span
span.setAttribute(1, forKey: "test")
spanCopy.setAttribute(2, forKey: "test")
span.end()
```

- performance - segment matadata may get really big (kilo bytes) and having to make a copy every time is not optimal

I think in 99% a reference type makes more sense, then again there *might* be cases when value type would work better, I dont know if it should be enforced that `Span` is a class; either way it does not affect `XRayRecorder.Segment` (which is a class)

---

the wrapper type mention in https://github.com/slashmo/gsoc-swift-tracing/pull/92#issuecomment-672833691 is an idea how to avoid using `SpanAttributes`

Personally I do not think its reasonable to enforce at the protocol that every `Span` uses (providing both getter and setter) `SpanAttributes` type;
there may be `TracingInstrument` implementations which will find it super convenient to use it,
as far X-Ray is concerned, `SpanAttributes` matches neither X-Ray attributes nor X-Ray metadata;
If `Span` protocol requires to implement it, I think to make a wrapper type with `SpanAttributes` and a segment:

```swift
internal struct SpanWithSegment: TracingInstrument.Span {
private let segment: XRayRecorder.Segment
var attributes: TracingInstrument.SpanAttributes
}
```
