### ISSUE TITLE
Consider grouping span attribute names in namespaces

### ISSUE THREAD

**Issue by pokryfka** [slashmo/gsoc-swift-tracing#135]
Just an idea...

I think this would compose better (plus much nicer generated documentation and autocompletion support):

```swift
extension SpanAttributeName {
    /// Semantic conventions for HTTP spans.
    public enum HTTP {
        public static let method = "http.method"
        public static let url = "http.url"
    }
}
```

than

```swift
extension SpanAttributeName {
    public static let httpMethod = "http.method"
    public static let httpURL = "http.url"
}
```

**Comment by ktoso** [comment]
Sounds good, that's not too much maintanance overhead thankfully. We only didn't want to copy all the docs to both the strings and real attributes, this should be good to do tho 👍

**Comment by slashmo** [comment]
@pokryfka Yeah, I like that too. Thanks for the suggestion 👍
