### ISSUE TITLE
Consider renaming TracingInstrument -> Tracer as it's a well known word

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#140]
And just "happens to be" an instrument as well.

It causes less typing in instrumented systems / user apps and is more familiar to existing users.
We should not make our API too annoying to use as people won't like it otherwise.

Our Tracer also aligns with OTel so that's good.

**Comment by slashmo** [comment]
Sounds good 👌 How about renaming the library to `Tracing` too, dropping the `Instrumentation` suffix?

**Comment by ktoso** [comment]
Yeah I think that sounds good, and it happens to be an instrumentation, I think that's fine 👍
