### ISSUE TITLE
ExtractorProtocol cannot handle multiple header fields

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#145]
Currently, `ExtractorProtocol` is defined with the following method requirement, which works well enough for single-field headers such as W3C TraceContexts `traceparent`.

```swift
func extract(key: String, from carrier: Carrier) -> String?
```

For `tracestate`, however, W3C TraceContext allows multiple header fields:

> TraceState *MAY* be sent or received as multiple header fields
> https://www.w3.org/TR/trace-context/#tracestate-header-field-values

Therefore, we should adapt our `ExtractorProtocol` to allow the extraction of multiple values for the same key.

In regards to `tracestate` the `InjectorProtocol` doesn't have to be changed:

> When receiving multiple `tracestate` header fields, they *MUST* be combined into a single header according to [RFC7230](https://httpwg.org/specs/rfc7230.html#field.order).
> https://www.w3.org/TR/trace-context/#tracestate-header-field-values

**Comment by slashmo** [comment]
@ktoso Might be a good opportunity to look into #59 & #60 again.

**Comment by ktoso** [comment]
a tracestate represented in many header fields is safe to "merge" into one string through, so that could be what we do here.

The question i think is more general, if we should become more generic here -- should the return type become some `Extracted` enum or should it become []... what would the cost be -- could benefit from doing a benchmark and analysis if we'd want to head for arrays here... not sure we need it in general 🤔 

What do you propose we do here -- what would the return signature be?

**Comment by slashmo** [comment]
I think an enum `Extracted` is a good idea. Let's say we have the following:

```swift
enum Extracted {
  case single(String)
  case many([String])
}

func extract(key: String, from carrier: Carrier) -> Extracted?
```

Then, instrument developers could handle the presence of multiple values on their own if needed.

**Comment by slashmo** [comment]
Maybe making the `Extracted` enum generic to replace the `String` types could be interesting as well. We might be able to combine that with the `BaggageContextKey.Value` in the method signature.

**Comment by slashmo** [comment]
@ktoso & I synced on this. For now, we agreed on keeping the method signature as-is and default `HTTPHeadersExtractor` to always extract all values for a given header name and then joining them comma-separated as recommended in the HTTP spec: https://httpwg.org/specs/rfc7230.html#rfc.section.3.2.2
