### ISSUE TITLE
inject() implementations should only be additive

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#25]
FakeTracer today does remove a header from headers if it's not in the baggage:

```
 else {
            headers.remove(name: Self.headerName)
        }
```

it should not do that; we should not be 'destructive' in inject() other than if we happen to override a header because we're setting headers from baggage.

Removing the else there will be enough here 👍

**Comment by slashmo** [comment]
Good catch, makes sense to remove the removal. 👍
