### ISSUE TITLE
Step 0: Sample (single threaded, no branch/join) of inject/extract-ing context

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#3]
Let's start at step zero before we take it further.

As we go through this project we'll want to cover a bunch of cases and samples ("scenarios") where and how to use the context.

Let's start at step zero and just have an example how in single threaded normal local code one might use the context to:

- inject some values
- pass around the context through some methods
- see that it's usable in there
- extract values from the context

--

From that step, we can start talking about "where the extract/inject code would live" (e.g. the "glue code" between context + a specific framework (http, other) + and specific tracer, and how we'd fit that in.

Once we have the general shape, let's continue to Step 1 (perhaps inject/extract from http headers), and continue adding more cases :) (we have them outlined in our project plan google doc, but let's take them one step at a time here)

**Comment by slashmo** [comment]
This has been implemented in #11. (Feel free to re-open if the example is still missing something)
