### ISSUE TITLE
First end-to-end sample (HTTPClient -> NIO Server -> ...)

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#33]
First sample in which we want to:

- have a client issue an http request (our "wrapped" http client for now)
  - a) with some values in context
  - b) without any values in context
- `inject` from context to headers
- receive on a server and `extract` the context
  - show that we got the same values 
  - show how an inject could "make up" a new trace id if none was present in incoming request
   - fun topic: showcase how we'd implement sampling here ("one in n requests should be traced") etc
- the server should log something, and these logs should include the metadata we got from the context

Maybe make another request from there?

**Comment by ktoso** [comment]
Made a ticket for what we're working towards in this period @slashmo 👍

**Comment by slashmo** [comment]
Great, thanks for adding this! I can get right to it once we figured out how to best integrate `swift-log` (#34). I like the idea of showcasing sampling with this. 👌
