### ISSUE TITLE
Logging performance considerations

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#38]
Currently, the computed `logger` property creates String representations (`String(describing: value)`) of everything inside the `BaggageContext`, although a logging configuration may not even print out this metadata.

One possibility suggested by @ktoso is to create a custom `LogHandler` that allows us to use the `String(describing: value)` call only when needed.

**Comment by ktoso** [comment]
Yup, and we can now prove that the optimizations matter or not, using the benchmark tools merged in https://github.com/slashmo/gsoc-swift-tracing/pull/39

**Comment by ktoso** [comment]
Working on this as part of #37
