### ISSUE TITLE
Consider nicer string description of baggage context

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#41]
Current printout just uses the default properties which is `BaggageContext(_storage: [:])` which reads a bit meh, since we want to hide that _storage.

Specifically, it looks like this today:

`BaggageContext(_storage: [Baggage.AnyBaggageContextKey(keyType: MyModule.MyFunKey, _name: nil): Baggage.BaggageContext.(unknown context at $10773422c).ValueContainer(value: ...)])`

That's a lot of noise :) 

Perhaps the default rendering should only render the keys?

**Comment by slashmo** [comment]
Agreed, that's an easy win for usability 👍
