### ISSUE TITLE
Instrument "box" naming

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#43]
(ignoring how the inject/extract to/from are expressed).

We'd want to write Instrument as the generic rather than `I` since that's common swift style to use full words.
But we today use Instrument for the wrapper type:

```swift
    init<Instrument>(instrument: Instrument)
        where Instrument: InstrumentProtocol,
        Instrument.InjectInto == HTTPHeaders,
        Instrument.ExtractFrom == HTTPHeaders {

        self.instrument = Instrument(instrument) // conflict
```

What would be a better naming strategy for this type:

```swift
/// A box-type for an `InstrumentProtocol`, necessary for creating homogeneous collections of `InstrumentProtocol`s.
public struct Instrument<InjectInto, ExtractFrom>: InstrumentProtocol {
    private let inject: (BaggageContext, inout InjectInto) -> Void
    private let extract: (ExtractFrom, inout BaggageContext) -> Void

    /// Wrap the given `InstrumentProtocol` inside an `Instrument`.
    /// - Parameter instrument: The `InstrumentProtocol` being wrapped.
    public init<I>(_ instrument: I)
        where
        I: InstrumentProtocol,
        I.InjectInto == InjectInto,
        I.ExtractFrom == ExtractFrom {
```

`TracingInstrument` does come to mind, but these ones are _not_ specifically tracing, they are generic.

Having looked at this again I guess this should be `AnyInstrument` and the protocol can become `InstrumentProtocol` (OR `BaggageInstrument`)... WDYT?

**Comment by slashmo** [comment]
> Having looked at this again I guess this should be `AnyInstrument` and the protocol can become `InstrumentProtocol`

Agreed. Calling the generic type argument `I` felt like a necessary workaround rather than a good solution. I think `AnyInstrument` more clearly communicates the intent 👍 I'd prefer `Instrument` for the protocol, but then we'd have to use `I` or something similar again, so I guess calling it `InstrumentProtocol` is worth the trade-off.

**Comment by ktoso** [comment]
Yeah, sounds like reasonable tradeoffs 👍
