### ISSUE TITLE
Design initial TracingInstrument protocol

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#50]
Inherits from `Instrument` to require span-related APIs

**Comment by ktoso** [comment]
Similar Tracer types to get inspiration from: 

- OT: https://github.com/opentracing/opentracing-swift/blob/edb593881737aec896420474a1ca45215f469f3e/Sources/OpenTracing/Tracer.swift (would be nice if it can be expressed using our protocol, as we'll want to be good citizens in an OT world as well)
- Brave: https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Tracer.java

Also related:
- https://tracingplane.github.io/tracingplane-java/doc/brown/tracingplane/TransitLayer.html how "instruments" are implemented in tracingplane
- how a Tracer is implemented over BaggageContext https://github.com/JonathanMace/tracingplane-opentracing/blob/master/src/main/java/brownsys/tracingplane/opentracing/OpenTracingPlane.java

**Comment by ktoso** [comment]
We want to ensure the following can be expressed easily:

- any OT tracer
- https://github.com/pokryfka/aws-xray-sdk-swift
- Maybe Instruments.app os_signpost based intervals represented as simple spans, for local debugging?
