### ISSUE TITLE
Consider using closures instead of injector/extractor types

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#60]
The only thing an `Extractor`/`Injector` has to implement is one method. That's why we could consider replacing these types with closures.

**Comment by slashmo** [comment]
@ktoso & I decided against using simple closures because it's easier to transition to possible method signature changes by creating default implementations for both old and new signatures.

**Comment by ktoso** [comment]
Thanks, yeah it's easier to evolve/add/deprecate APIs if we'd ever need to (same like we did with log handlers in swift-log)

**Comment by ktoso** [comment]
Assigned milestone.
