### ISSUE TITLE
Add OT semantic convention extensions to SpanAttribute

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#65]
As our `Span` & `SpanAttribute` are very much inspired by the OpenTelemetry spec, we might consider adding their semantic conventions as extensions to the `Instrumentation` library as well: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md

https://github.com/slashmo/gsoc-swift-tracing/pull/62#discussion_r451946892

**Comment by pokryfka** [comment]
related with https://github.com/pokryfka/aws-xray-sdk-swift/issues/22

Would be great to have type safe (enum or static string literals) [Semantic conventions for HTTP spans](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md)

as well as some mappings / convenience methods from `HTTP code` to `Span status code`, see https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md

example how it could be used in https://github.com/slashmo/gsoc-swift-tracing/issues/95#issue-665109528

**Comment by slashmo** [comment]
I’m not sure yet where to put these extensions. I think they’re very valuable and should be added somewhere, but I don’t know if polluting the `Instrumentation` library is the best way to do it. What do you think about an additional library, e.g. `OpenTelemetryInstrumentationSupport`? CC @ktoso & @pokryfka

**Comment by ktoso** [comment]
A module `OpenTelemetryInstrumentationSupport` with extensions on the types sounds good to me 👍 

Note that _not just HTTP_ 😉 There's more things here: https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions
