### ISSUE TITLE
Remove tracing instrument current span

### ISSUE THREAD

**Issue by ktoso** [slashmo/gsoc-swift-tracing#74]
Proposing to remove 'tracingInstrument.currentSpan' completely from our APIs 

Thinking some more about it I think we should be doubling down on the fact that we need to pass context around explicitly and let's not try to offer the thread local workaround. If we need to we could revisit this but for now let's remove it and not dive into the world of scope managers at all, as were on the side of explicitly context passing already anyway. 

The main reason is that we want baggage context to be agnostic to any implementation of even tracing and thus everyone should be able to adopt it. And, since there are so many concurrency stories in swift it will be hard or impossible to implement a thread local style current span that actually works reliably - e.g. across nio that then uses dispatch that then uses some couritines etc... let's not assume we are able to solve this for the time being.

**Comment by slashmo** [comment]
@ktoso Agreed.

> as were on the side of explicitly context passing already anyway

Good point 👌

I'll remove it from the API.
