### ISSUE TITLE
Make Span attributes write-only

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#87]
Currently `Span` attributes are modeled through two types `SpanAttributes` & `SpanAttribute`. To make conformance to the `Span` protocol easier we want to drop these types from the public API and instead expose methods on `Span` for the different primitives, e.g. `setAttribute(_ string: String, forKey key: String)` instead of the subscript-based `attributes` property.

**Comment by ktoso** [comment]
Note that this changes a bit since we now do the subscript keypath based attributes; perhaps this task is moot now?

**Comment by pokryfka** [comment]
> After the Span is created, it SHOULD be possible to change the its name, set its Attributes, and add Links and Events.

> Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanContext.

Other than the "attributes" attributes, is it needed  to keep getter for:

- startTimestamp
- endTimestamp
- status
- kind

?

**Comment by ktoso** [comment]
It's not required, just that noone got to removing the getters yet -- PR welcome!

**Comment by pokryfka** [comment]
> It's not required, just that noone got to removing the getters yet -- PR welcome!

https://github.com/slashmo/gsoc-swift-tracing/pull/127
