### ISSUE TITLE
Add error recording API to Span

### ISSUE THREAD

**Issue by slashmo** [slashmo/gsoc-swift-tracing#90]
> To facilitate recording an exception languages SHOULD provide a RecordException convenience method. The signature of the method is to be determined by each language and can be overloaded as appropriate. The method MUST record an exception as an Event with the conventions outlined in the exception semantic conventions document.

According to the Otel spec, exceptions must be recorded as `SpanEvent`: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/exceptions.md

**Comment by slashmo** [comment]
If we implement this following the spec I think this could be a convenience method on `Span`. @pokryfka Would love to get your input on this. If events don't work well for XRay we could also add it as a protocol requirement on `Span` and default it to the "event-way" in an extension. Then you could still overwrite the method in your `Span`-conforming type.

**Comment by pokryfka** [comment]
> we could also add it as a protocol requirement on Span

please do

**Comment by pokryfka** [comment]
I found the issue but I am in mobile and cannot really see if it was changed or not after all - will check on computer later on.

Link for reference: https://forums.swift.org/t/overriding-protocol-default-implementation/5147

If it’s not possible to override protocol default implementation, then I would ask to keep the methods separate or provide a way to check if Event was an Exception

**Comment by pokryfka** [comment]
made a quick test in Playground (Swift5.2):

```swift
protocol Span {
    func a() -> String
}

extension Span {
    // default implementation of a function defined by the protocol
    func a() -> String { "default A" }
    
    // extend the protocol with a convinience method not explictly defined by the protocol
    func b() -> String { "default B" }
}

class C1: Span {}

let c1: Span = C1()
c1.a() // default A
c1.b() // default B

class C2: Span {
    func a() -> String { "C2 A" }
    func b() -> String { "C2 B" }
}

let c2: Span = C2()
c2.a() // C2 A
c2.b() // default B

struct S2: Span {
    func a() -> String { "S2 A" }
    func b() -> String { "S2 B" }
}

let s2: Span = S2()
s2.a() // S2 A
s2.b() // default B
```

so it has not changed since the issue about confusion with "overloading" and "shadowing" default methods

---

so - I can override default implementation as long as the function is part of the protocol

please do define function to `reportException` in `Span` protocol

you may or may not provide its default implementation
(I am planning to provide different implementations for `addEvent` and `reportException`)
